### ISSUE TITLE
5 tests are failing

### ISSUE THREAD

**Issue by henry-hz** [KazuCocoa/http_proxy#26]
Dear @KazuCocoa ,
thanks for sharing the lib. 
5 tests are failing in my machine. 

Mix 1.3.0-dev
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

[test.txt](https://github.com/KazuCocoa/http_proxy/files/311597/test.txt)

**Comment by KazuCocoa** [comment]
Thanks!
I'll check it.

**Comment by KazuCocoa** [comment]
@henry-hz
Hi, failing tests should fixed with https://github.com/KazuCocoa/http_proxy/issues/28 .

In `HttpProxyFile.json_files/1`, I use `File.ls/1` to read files. So, some tests failed because of order of files  and it may depend on environment of machine, I guess.
I fixed failed tests to improve tests not to depend on order of list.

**Comment by henry-hz** [comment]
thank you :+1:
